global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.Extensions.Hosting;
global using System.Collections.Generic;
global using System.Reflection.Emit;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using AutomapperProfile = AutoMapper.Profile;
global using ForumAppJWTAzure.Server.Data;
global using ForumAppJWTAzure.Shared.Models.User;
global using ForumAppJWTAzure.Shared.ViewModels;
global using Serilog;
